// Generated by gencpp from file kuka_cv/RequestPalette.msg
// DO NOT EDIT!


#ifndef KUKA_CV_MESSAGE_REQUESTPALETTE_H
#define KUKA_CV_MESSAGE_REQUESTPALETTE_H

#include <ros/service_traits.h>


#include <kuka_cv/RequestPaletteRequest.h>
#include <kuka_cv/RequestPaletteResponse.h>


namespace kuka_cv
{

struct RequestPalette
{

typedef RequestPaletteRequest Request;
typedef RequestPaletteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestPalette
} // namespace kuka_cv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_cv::RequestPalette > {
  static const char* value()
  {
    return "597d1430c10def3fddb3fe4385dd70e9";
  }

  static const char* value(const ::kuka_cv::RequestPalette&) { return value(); }
};

template<>
struct DataType< ::kuka_cv::RequestPalette > {
  static const char* value()
  {
    return "kuka_cv/RequestPalette";
  }

  static const char* value(const ::kuka_cv::RequestPalette&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_cv::RequestPaletteRequest> should match
// service_traits::MD5Sum< ::kuka_cv::RequestPalette >
template<>
struct MD5Sum< ::kuka_cv::RequestPaletteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_cv::RequestPalette >::value();
  }
  static const char* value(const ::kuka_cv::RequestPaletteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_cv::RequestPaletteRequest> should match
// service_traits::DataType< ::kuka_cv::RequestPalette >
template<>
struct DataType< ::kuka_cv::RequestPaletteRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_cv::RequestPalette >::value();
  }
  static const char* value(const ::kuka_cv::RequestPaletteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_cv::RequestPaletteResponse> should match
// service_traits::MD5Sum< ::kuka_cv::RequestPalette >
template<>
struct MD5Sum< ::kuka_cv::RequestPaletteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_cv::RequestPalette >::value();
  }
  static const char* value(const ::kuka_cv::RequestPaletteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_cv::RequestPaletteResponse> should match
// service_traits::DataType< ::kuka_cv::RequestPalette >
template<>
struct DataType< ::kuka_cv::RequestPaletteResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_cv::RequestPalette >::value();
  }
  static const char* value(const ::kuka_cv::RequestPaletteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_CV_MESSAGE_REQUESTPALETTE_H
