// Generated by gencpp from file kuka_cv/RequestPaletteRequest.msg
// DO NOT EDIT!


#ifndef KUKA_CV_MESSAGE_REQUESTPALETTEREQUEST_H
#define KUKA_CV_MESSAGE_REQUESTPALETTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_cv
{
template <class ContainerAllocator>
struct RequestPaletteRequest_
{
  typedef RequestPaletteRequest_<ContainerAllocator> Type;

  RequestPaletteRequest_()
    : mode(0)  {
    }
  RequestPaletteRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestPaletteRequest_

typedef ::kuka_cv::RequestPaletteRequest_<std::allocator<void> > RequestPaletteRequest;

typedef boost::shared_ptr< ::kuka_cv::RequestPaletteRequest > RequestPaletteRequestPtr;
typedef boost::shared_ptr< ::kuka_cv::RequestPaletteRequest const> RequestPaletteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator1> & lhs, const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator1> & lhs, const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_cv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "418c02483a8ca57215fb7b31c5c87234";
  }

  static const char* value(const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x418c02483a8ca572ULL;
  static const uint64_t static_value2 = 0x15fb7b31c5c87234ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_cv/RequestPaletteRequest";
  }

  static const char* value(const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n"
;
  }

  static const char* value(const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestPaletteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_cv::RequestPaletteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_cv::RequestPaletteRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_CV_MESSAGE_REQUESTPALETTEREQUEST_H
